### ISSUE TITLE
Non-Session Instance Filter

### ISSUE THREAD

**Issue by ghost** [UnionSoft/sysstate#7]
Nu moet je je cookies weggooien om terug te komen naar een werkende view als je een foutmelding krijgt, want je kunt heeeel makkelijk foutmeldingen krijgen door simpelweg iets aan te klikken.

Filter configuratie kan in URL, mogelijk ondersteund door bitmap/bitswitch

**Comment by cjhkramer** [comment]
1.6.12 now uses rest calls for filtering
