### ISSUE TITLE
Configuratie eenvoudiger maken

### ISSUE THREAD

**Issue by ghost** [UnionSoft/sysstate#8]
I.p.v. tig schermen, gewoon 1 scherm waar je alles in kunt doen voor 1 app (Project)
- Meerdere instances tegelijk bewerken
- Voorzet voor verschillende omgevingen (o.i.d)
- Multi environment state configureren, middels parameters dynamisch url kan opbouwen.

**Comment by cjhkramer** [comment]
Use the API
